import { useEffect, useState } from 'react'
import { analyticsExportUrl, getAnalytics, type AnalyticsResponse } from '../services/apiClient'
import { userFacingApiError } from '../utils/logger'

export function ExportControlPage() {
  const [data, setData] = useState<AnalyticsResponse | null>(null); const [error, setError] = useState('')
  const load = () => { setError(''); getAnalytics().then(setData).catch(reason => setError(userFacingApiError(reason, 'Analytics could not be loaded.'))) }
  useEffect(() => { load() }, [])
  return <div className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--royal-blue)]">Export Control</p><h1 className="display mt-2 text-4xl font-bold text-[var(--royal-blue)]">Workflow analytics</h1><p className="mt-2 text-sm text-[var(--muted)]">Database-backed request and visit activity.</p></header>{error && <p role="alert" className="border border-[#e1b5b5] bg-[#fff4f4] p-4 text-sm text-[#9b2c2c]">{error}</p>}{data && <><div className="flex flex-wrap gap-3"><a download href={analyticsExportUrl('csv')} className="rounded-[4px] border border-[var(--royal-blue)] px-4 py-2 text-sm font-semibold text-[var(--royal-blue)]">Export CSV</a><a download href={analyticsExportUrl('xlsx')} className="rounded-[4px] bg-[var(--royal-blue)] px-4 py-2 text-sm font-semibold text-white">Export XLSX</a></div><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Total requests" value={data.totalRequests} />{Object.entries(data.byStatus).slice(0, 3).map(([status, count]) => <Metric key={status} label={status.replaceAll('_', ' ')} value={count} />)}</section><section className="overflow-x-auto border border-[var(--silver)] bg-white p-6"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-[var(--silver)]"><th className="p-2">Request</th><th className="p-2">Visitor</th><th className="p-2">Visit date</th><th className="p-2">Status</th></tr></thead><tbody>{data.rows.map(row => <tr key={`${row.requestNumber}-${row.visitDate}`} className="border-b border-[var(--silver)]"><td className="p-2">{row.requestNumber}</td><td className="p-2">{row.visitor || 'Visitor form pending'}</td><td className="p-2">{row.visitDate || 'Not scheduled'}</td><td className="p-2">{row.status}</td></tr>)}</tbody></table></section></>}</div>
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="border border-[var(--silver)] bg-white p-5"><p className="text-xs uppercase tracking-wide text-[var(--muted)]">{label}</p><p className="mt-3 text-2xl font-semibold text-[var(--royal-blue)]">{value}</p></div> }
