import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getNotifications, getSecurityVisitors, listVisitorRequests, markNotificationRead, type NotificationItem, type SecurityVisitor, type VisitorRequestListItem } from '../services/apiClient'
import { userFacingApiError } from '../utils/logger'

export function PendingActionsPage() { const [items, setItems] = useState<VisitorRequestListItem[]>([]); const [error, setError] = useState(''); useEffect(() => { listVisitorRequests().then((result) => setItems(result.items.filter((item) => ['VISITOR_FORM_PENDING', 'HOST_REVIEW', 'DPS_PENDING', 'EC_REVIEW', 'PENDING_DOCUMENTATION', 'SECURITY_HOLD_EC_REVIEW'].includes(item.currentStatus)))).catch((reason) => setError(userFacingApiError(reason, 'Pending actions could not be loaded.')))}, []); return <OperationalFrame title="Pending actions" error={error}>{items.length ? <RequestRows items={items} /> : <p className="text-sm text-[var(--muted)]">No pending actions.</p>}</OperationalFrame> }

export function SecurityPage() { const [items, setItems] = useState<SecurityVisitor[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const load = () => getSecurityVisitors(query).then(setItems).catch((reason) => setError(userFacingApiError(reason, 'Security visitors could not be loaded.'))); useEffect(() => { void load() }, []); return <OperationalFrame title="Security" error={error}><div className="mb-5 flex gap-2"><input aria-label="Search security visitors" className="w-full border border-[var(--silver)] px-3 py-2" placeholder="Search visitor, company or request" value={query} onChange={(event) => setQuery(event.target.value)} /><button type="button" onClick={load} className="bg-[var(--royal-blue)] px-4 py-2 text-sm font-semibold text-white">Search</button></div>{items.length ? <div className="space-y-2">{items.map((item) => <Link key={item.id} to={`/visitor-requests/${item.requestId}`} className="flex flex-wrap justify-between gap-2 border-b border-[var(--silver)] py-3 text-sm"><span><strong>{item.visitorName}</strong><span className="ml-3 text-[var(--muted)]">{item.company}</span></span><span className="text-[var(--royal-blue)]">{item.status}</span></Link>)}</div> : <p className="text-sm text-[var(--muted)]">No approved visitors found.</p>}</OperationalFrame> }

export function NotificationsPage() { const [items, setItems] = useState<NotificationItem[]>([]); const [error, setError] = useState(''); const load = () => getNotifications().then(setItems).catch((reason) => setError(userFacingApiError(reason, 'Notifications could not be loaded.'))); useEffect(() => { void load() }, []); const read = async (id: string) => { try { await markNotificationRead(id); setItems((current) => current.map((item) => item.id === id ? { ...item, isRead: true } : item)) } catch (reason) { setError(userFacingApiError(reason, 'Notification could not be updated.')) } }; return <OperationalFrame title="Notifications" error={error}>{items.length ? <div className="divide-y divide-[var(--silver)]">{items.map((item) => <button key={item.id} type="button" onClick={() => void read(item.id)} className={`block w-full py-4 text-left text-sm ${item.isRead ? 'text-[var(--muted)]' : 'font-semibold text-[var(--ink)]'}`}>{item.message}<span className="mt-1 block text-xs text-[var(--muted)]">{item.type} · {new Date(item.createdAt).toLocaleString()}</span></button>)}</div> : <p className="text-sm text-[var(--muted)]">No notifications yet.</p>}</OperationalFrame> }

function OperationalFrame({ title, error, children }: { title: string; error: string; children: React.ReactNode }) { return <div className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--royal-blue)]">RRVMS workspace</p><h1 className="display mt-2 text-4xl font-bold text-[var(--royal-blue)]">{title}</h1></header>{error && <p role="alert" className="border border-[#e1b5b5] bg-[#fff4f4] p-4 text-sm text-[#9b2c2c]">{error}</p>}<section className="border border-[var(--silver)] bg-white p-6">{children}</section></div> }
function RequestRows({ items }: { items: VisitorRequestListItem[] }) { return <div className="divide-y divide-[var(--silver)]">{items.map((item) => <Link key={item.id} to={`/visitor-requests/${item.id}`} className="flex flex-wrap justify-between gap-2 py-4 text-sm"><span><strong className="text-[var(--royal-blue)]">{item.requestNumber}</strong><span className="ml-3">{item.visitorName}</span></span><span className="text-[var(--muted)]">{item.currentStatus}</span></Link>)}</div> }