import { useCallback, useEffect, useState, type ReactNode } from 'react'
import { Link, useParams } from 'react-router-dom'
import { executeVisitorRequestAction, getVisitorRequest, type VisitorRequestDetail } from '../services/apiClient'
import { userFacingApiError } from '../utils/logger'
import { useAuth } from '../auth/useAuth'

export function VisitorRequestDetailPage() {
  const { id = '' } = useParams()
  const { user } = useAuth()
  const [request, setRequest] = useState<VisitorRequestDetail | null>(null)
  const [error, setError] = useState('')
  const [actionError, setActionError] = useState('')
  const [acting, setActing] = useState(false)
  const load = useCallback(async () => { try { setRequest(await getVisitorRequest(id)); setError('') } catch (reason) { setError(userFacingApiError(reason, 'Request details could not be loaded.')) } }, [id])
  useEffect(() => { const run = async () => { await load() }; void run() }, [load])
  const runAction = async (action: string, values: Record<string, string> = {}) => { setActing(true); setActionError(''); try { setRequest(await executeVisitorRequestAction(id, { action, ...values })) } catch (reason) { setActionError(userFacingApiError(reason, 'That workflow action could not be completed.')) } finally { setActing(false) } }
  if (error) return <div className="space-y-3"><p role="alert" className="border border-[#e1b5b5] bg-[#fff4f4] p-4 text-sm text-[#9b2c2c]">{error}</p><button type="button" onClick={() => void load()} className="font-semibold text-[var(--royal-blue)] underline">Retry</button></div>
  if (!request) return <p className="text-sm text-[var(--muted)]">Loading request...</p>
  const status = request.currentStatus
  return <div className="space-y-6"><Link to="/visitor-requests" className="text-sm font-semibold text-[var(--royal-blue)]">&lt;- Visitor requests</Link><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--royal-blue)]">Request detail</p><h1 className="display mt-2 text-4xl font-bold text-[var(--royal-blue)]">{request.requestNumber}</h1><p className="mt-2 text-sm text-[var(--muted)]">{request.visitor.fullName} · {status}</p></div><Actions role={user?.role ?? ''} status={status} acting={acting} onAction={runAction} />{actionError && <p role="alert" className="w-full text-sm text-[#9b2c2c]">{actionError}</p>}</header><section className="grid gap-6 lg:grid-cols-2"><Info title="Visitor"><p>{request.visitor.fullName}</p><p>{request.visitor.companyName} · {request.visitor.designation}</p><p>{request.visitor.country} · {request.visitor.citizenship}</p><p>{request.visitor.idType} ending {request.visitor.idLast4}</p></Info><Info title="Visit"><p>{request.visitingCompany} · {request.visitingSite}</p><p>{request.visitPurposeType}</p><p>{request.purpose}</p></Info><Info title="Visit days"><div className="space-y-2">{request.visitDays.map((day) => <p key={day.id}>{day.visitDate} · {day.status}{day.expectedArrivalTime ? ` · ${day.expectedArrivalTime}` : ''}</p>)}</div></Info><Info title="Assets"><div className="space-y-2">{request.assets.length ? request.assets.map((asset) => <p key={asset.id}>{asset.assetType} · {asset.verificationStatus}</p>) : <p>No declared assets.</p>}</div></Info></section><Info title="Audit history"><div className="space-y-3">{request.auditHistory.length ? request.auditHistory.map((entry) => <p key={entry.id}><strong>{entry.action}</strong> · {entry.details} <span className="text-[var(--muted)]">{new Date(entry.createdAt).toLocaleString()}</span></p>) : <p>No audit entries.</p>}</div></Info></div>
}

function Actions({ role, status, acting, onAction }: { role: string; status: string; acting: boolean; onAction: (action: string, values?: Record<string, string>) => Promise<void> }) { const button = (action: string, label: string, values?: Record<string, string>) => <button disabled={acting} type="button" onClick={() => { const key = values?.idLast4 === '__prompt__' ? 'idLast4' : values?.badgeNumber === '__prompt__' ? 'badgeNumber' : ''; const value = key ? window.prompt(key === 'idLast4' ? 'Enter the four ID digits' : 'Enter the daily badge number') ?? '' : ''; void onAction(action, { ...values, ...(key ? { [key]: value } : {}) }) }} className="rounded-[4px] bg-[var(--royal-blue)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{label}</button>; const canHost = ['Requester', 'Host', 'Admin'].includes(role); const canEc = ['ExportControl', 'Admin'].includes(role); const canSecurity = ['Security', 'Admin'].includes(role); return <div className="flex flex-wrap gap-2">{canHost && status === 'VISITOR_FORM_PENDING' && button('visitor-submit', 'Visitor submitted')}{canHost && ['HOST_REVIEW', 'VISITOR_FORM_PENDING'].includes(status) && button('host-submit', 'Final submit')}{canHost && ['DPS_PENDING', 'HOST_DPS', 'EC_DPS_REVIEW'].includes(status) && button('dps', 'Complete DPS', { comment: 'Clear' })}{canEc && ['EC_REVIEW', 'EC_RE_REVIEW_REQUIRED', 'SECURITY_HOLD_EC_REVIEW'].includes(status) && <>{button('ec-approve', 'Approve', { comment: 'Approved' })}{button('ec-reject', 'Reject', { reason: 'Rejected after review' })}{button('ec-request-documents', 'Request documents', { reason: 'Additional documentation required' })}</>}{canHost && status === 'PENDING_DOCUMENTATION' && button('submit-documents', 'Submit documents', { comment: 'Supporting documentation submitted' })}{canSecurity && status === 'APPROVED' && button('verify', 'Verify visitor', { idLast4: '__prompt__' })}{canSecurity && status === 'SECURITY_VERIFICATION' && button('check-in', 'Check in', { badgeNumber: '__prompt__' })}{canSecurity && status === 'CHECKED_IN' && button('check-out', 'Check out')}</div> }
function Info({ title, children }: { title: string; children: ReactNode }) { return <section className="border border-[var(--silver)] bg-white p-6"><h2 className="display text-xl font-bold text-[var(--royal-blue)]">{title}</h2><div className="mt-4 space-y-2 text-sm text-[var(--ink)]">{children}</div></section> }
