import { useState, type FormEvent } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { countries } from '../data/countries'
import { submitVisitorForm, type VisitorForm } from '../services/apiClient'
import { userFacingApiError } from '../utils/logger'

const initialForm: VisitorForm = { fullName: '', citizenship: '', country: '', designation: '', companyName: '', officeCity: '', officeCountry: '', telephone: '', email: '', idType: 'Passport', idLast4: '', assets: [] }

export function VisitorFormPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(initialForm); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const update = <K extends keyof VisitorForm>(field: K, value: VisitorForm[K]) => setForm(current => ({ ...current, [field]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (!/^\d{4}$/.test(form.idLast4)) return setError('ID last 4 must contain exactly four digits.'); setSaving(true); try { await submitVisitorForm(id, form); navigate('/login') } catch (reason) { setError(userFacingApiError(reason, 'The visitor form could not be submitted.')) } finally { setSaving(false) } }
  const updateAsset = (index: number, field: keyof VisitorForm['assets'][number], value: string) => setForm(current => ({ ...current, assets: current.assets.map((asset, assetIndex) => assetIndex === index ? { ...asset, [field]: value } : asset) }))
  return <form onSubmit={submit} className="mx-auto max-w-4xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--royal-blue)]">RRVMS visitor form</p><h1 className="display mt-2 text-4xl font-bold text-[var(--royal-blue)]">Visitor information</h1><p className="mt-2 text-sm text-[var(--muted)]">Only the last four digits of your identity number are collected.</p></header>{error && <p role="alert" className="border border-[#e1b5b5] bg-[#fff4f4] p-4 text-sm text-[#9b2c2c]">{error}</p>}<section className="grid gap-4 border border-[var(--silver)] bg-white p-6 sm:grid-cols-2"><Field label="Full legal name" value={form.fullName} onChange={value => update('fullName', value)} required /><Field label="Company" value={form.companyName} onChange={value => update('companyName', value)} required /><Select label="Citizenship" value={form.citizenship} onChange={value => update('citizenship', value)} /><Select label="Country" value={form.country} onChange={value => update('country', value)} /><Field label="Designation" value={form.designation} onChange={value => update('designation', value)} /><Field label="Office city" value={form.officeCity} onChange={value => update('officeCity', value)} /><Select label="Office country" value={form.officeCountry} onChange={value => update('officeCountry', value)} /><Field label="Telephone" value={form.telephone} onChange={value => update('telephone', value)} required /><Field label="Email" type="email" value={form.email} onChange={value => update('email', value)} required /><Select label="ID type" value={form.idType} onChange={value => update('idType', value)} options={['Passport', 'Visa', 'Government ID', 'Other valid ID proof']} /><Field label="ID last 4 digits" value={form.idLast4} onChange={value => update('idLast4', value.replace(/\D/g, '').slice(0, 4))} required /></section><section className="border border-[var(--silver)] bg-white p-6"><h2 className="display text-xl font-bold text-[var(--royal-blue)]">Declared assets</h2>{form.assets.map((asset, index) => <div key={index} className="mt-4 grid gap-4 sm:grid-cols-3"><Field label="Asset type" value={asset.assetType} onChange={value => updateAsset(index, 'assetType', value)} required /><Field label="Description" value={asset.description} onChange={value => updateAsset(index, 'description', value)} /><Field label="Serial number" value={asset.serialNumber} onChange={value => updateAsset(index, 'serialNumber', value)} required /></div>)}<button type="button" className="mt-4 text-sm font-semibold text-[var(--royal-blue)]" onClick={() => setForm(current => ({ ...current, assets: [...current.assets, { assetType: '', description: '', serialNumber: '' }] }))}>+ Add asset</button></section><button disabled={saving} className="rounded-[4px] bg-[var(--royal-blue)] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Submitting...' : 'Submit visitor form'}</button></form>
}
function Field({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="text-sm font-semibold text-[var(--ink)]">{label}<input required={required} type={type} value={value} onChange={event => onChange(event.target.value)} className="mt-2 block w-full border border-[var(--silver)] px-3 py-2.5 font-normal" /></label> }
function Select({ label, value, onChange, options = countries as unknown as string[] }: { label: string; value: string; onChange: (value: string) => void; options?: string[] }) { return <label className="text-sm font-semibold text-[var(--ink)]">{label}<select required className="mt-2 block w-full border border-[var(--silver)] bg-white px-3 py-2.5 font-normal" value={value} onChange={event => onChange(event.target.value)}><option value="">Select...</option>{options.map(option => <option key={option}>{option}</option>)}</select></label> }
