<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\RRVMS.Application\RRVMS.Application.csproj" />
    <ProjectReference Include="..\RRVMS.Infrastructure\RRVMS.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Identity.Web" />
  </ItemGroup>
</Project>

