using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using RRVMS.Api.Data;
using RRVMS.Api.DTOs;
using RRVMS.Api.Models;

namespace RRVMS.Api.Services;

public interface IVisitorRequestService
{
    Task<(IReadOnlyList<VisitorRequestListItemDto> Items, int Total)> ListAsync(int page, int pageSize, CancellationToken cancellationToken);
    Task<VisitorRequestDetailDto?> GetAsync(Guid id, CancellationToken cancellationToken);
    Task<VisitorRequestDetailDto> CreateAsync(CreateVisitorRequestDto input, string requesterKey, CancellationToken cancellationToken);
    Task<VisitorRequestDetailDto> ExecuteActionAsync(Guid requestId, WorkflowActionDto input, string userId, string role, CancellationToken cancellationToken);
    Task<VisitorFormDto?> GetVisitorFormAsync(Guid formId, CancellationToken cancellationToken);
    Task SubmitVisitorFormAsync(Guid formId, VisitorFormDto input, CancellationToken cancellationToken);
    Task SubmitAdditionalVisitorFormAsync(Guid formId, VisitorFormDto input, CancellationToken cancellationToken);
}

public sealed class VisitorRequestService(RrvmsDbContext db) : IVisitorRequestService
{
    public async Task<VisitorFormDto?> GetVisitorFormAsync(Guid formId, CancellationToken ct)
    {
        var form = await db.VisitorForms.AsNoTracking().FirstOrDefaultAsync(item => item.Id == formId, ct);
        return form is null ? null : new VisitorFormDto { FullName = form.FullName, Citizenship = form.Citizenship, Country = form.Country, Designation = form.Designation, CompanyName = form.CompanyName, OfficeCity = form.OfficeCity, OfficeCountry = form.OfficeCountry, Telephone = form.Telephone, Email = form.Email, IdType = form.IdType, IdLast4 = form.IdLast4 };
    }

    public async Task SubmitVisitorFormAsync(Guid formId, VisitorFormDto input, CancellationToken ct)
    {
        if (!CountryCatalog.IsValid(input.Country) || !CountryCatalog.IsValid(input.Citizenship) || !CountryCatalog.IsValid(input.OfficeCountry)) throw new ArgumentException("Country and citizenship must be selected from the country list.");
        if (!System.Text.RegularExpressions.Regex.IsMatch(input.IdLast4, "^[0-9]{4}$")) throw new ArgumentException("ID last 4 must contain exactly four digits.");
        var form = await db.VisitorForms.Include(item => item.VisitorRequest).ThenInclude(request => request.Visitor).FirstOrDefaultAsync(item => item.Id == formId, ct) ?? throw new KeyNotFoundException("Visitor form was not found.");
        if (form.Status is "SUBMITTED" or "APPROVED") throw new InvalidOperationException("This visitor form has already been submitted.");
        if (string.IsNullOrWhiteSpace(input.FullName)) throw new ArgumentException("Full legal name is required.");
        var now = DateTimeOffset.UtcNow; form.FullName = input.FullName.Trim(); form.Citizenship = input.Citizenship.Trim(); form.Country = input.Country.Trim(); form.Designation = input.Designation.Trim(); form.CompanyName = input.CompanyName.Trim(); form.OfficeCity = input.OfficeCity.Trim(); form.OfficeCountry = input.OfficeCountry.Trim(); form.Telephone = input.Telephone.Trim(); form.Email = input.Email.Trim(); form.IdType = input.IdType.Trim(); form.IdLast4 = input.IdLast4; form.Status = "SUBMITTED"; form.SubmittedAt = now; form.UpdatedAt = now;
        var visitor = form.Visitor; visitor.FullName = form.FullName; visitor.Citizenship = form.Citizenship; visitor.Country = form.Country; visitor.Designation = form.Designation; visitor.CompanyName = form.CompanyName; visitor.Phone = form.Telephone; visitor.Email = form.Email; visitor.IdType = form.IdType; visitor.IdLast4 = form.IdLast4; visitor.UpdatedAt = now;
        foreach (var asset in input.Assets) db.Assets.Add(new Asset { Id = Guid.NewGuid(), VisitorRequestId = form.VisitorRequestId, AssetType = asset.AssetType.Trim(), Description = asset.Description.Trim(), SerialNumber = asset.SerialNumber.Trim(), IsDeclared = true, VerificationStatus = AssetVerificationStatus.NotVerified, CreatedAt = now, UpdatedAt = now });
        db.VisitorFormVersions.Add(CreateVersion(form, input.Assets, 1, now));
        form.VisitorRequest.Status = RequestStatus.VISITOR_FORM_SUBMITTED; form.VisitorRequest.UpdatedAt = now; db.Notifications.Add(new Notification { Id = Guid.NewGuid(), UserId = form.VisitorRequest.RequesterId, Type = "VISITOR_FORM_COMPLETED", Message = "The visitor form has been completed and is ready for host review.", CreatedAt = now }); db.AuditLogs.Add(new AuditLog { Id = Guid.NewGuid(), Action = "VISITOR_FORM_SUBMITTED", EntityType = nameof(VisitorRequest), EntityId = form.VisitorRequestId, Details = "Visitor form submitted.", CreatedAt = now });
        await db.SaveChangesAsync(ct);
    }

    public async Task SubmitAdditionalVisitorFormAsync(Guid formId, VisitorFormDto input, CancellationToken ct)
    {
        if (!CountryCatalog.IsValid(input.Country) || !CountryCatalog.IsValid(input.Citizenship) || !CountryCatalog.IsValid(input.OfficeCountry)) throw new ArgumentException("Country and citizenship must be selected from the country list.");
        if (string.IsNullOrWhiteSpace(input.FullName) || !System.Text.RegularExpressions.Regex.IsMatch(input.IdLast4, "^[0-9]{4}$")) throw new ArgumentException("Full legal name and exactly four ID digits are required.");
        var form = await db.VisitorForms.Include(item => item.VisitorRequest).ThenInclude(request => request.Visitor).FirstOrDefaultAsync(item => item.Id == formId, ct) ?? throw new KeyNotFoundException("Visitor form was not found.");
        var now = DateTimeOffset.UtcNow; form.FullName = input.FullName.Trim(); form.Citizenship = input.Citizenship.Trim(); form.Country = input.Country.Trim(); form.Designation = input.Designation.Trim(); form.CompanyName = input.CompanyName.Trim(); form.OfficeCity = input.OfficeCity.Trim(); form.OfficeCountry = input.OfficeCountry.Trim(); form.Telephone = input.Telephone.Trim(); form.Email = input.Email.Trim(); form.IdType = input.IdType.Trim(); form.IdLast4 = input.IdLast4; form.Status = "SUBMITTED"; form.SubmittedAt = now; form.UpdatedAt = now;
        var visitor = form.Visitor; visitor.FullName = form.FullName; visitor.Citizenship = form.Citizenship; visitor.Country = form.Country; visitor.Designation = form.Designation; visitor.CompanyName = form.CompanyName; visitor.Phone = form.Telephone; visitor.Email = form.Email; visitor.IdType = form.IdType; visitor.IdLast4 = form.IdLast4; visitor.UpdatedAt = now;
        var version = await db.VisitorFormVersions.CountAsync(item => item.VisitorFormId == formId, ct) + 1; db.VisitorFormVersions.Add(CreateVersion(form, input.Assets, version, now));
        foreach (var asset in input.Assets) db.Assets.Add(new Asset { Id = Guid.NewGuid(), VisitorRequestId = form.VisitorRequestId, AssetType = asset.AssetType.Trim(), Description = asset.Description.Trim(), SerialNumber = asset.SerialNumber.Trim(), IsDeclared = true, VerificationStatus = AssetVerificationStatus.NotVerified, CreatedAt = now, UpdatedAt = now });
        var pending = await db.AdditionalInformationRequests.Where(item => item.VisitorRequestId == form.VisitorRequestId && item.Status == "PENDING").OrderByDescending(item => item.CreatedAt).FirstOrDefaultAsync(ct); if (pending is not null) { pending.Status = "SUBMITTED"; pending.RespondedAt = now; pending.ResponseSummary = form.FullName; pending.UpdatedAt = now; }
        form.VisitorRequest.Status = RequestStatus.DOCUMENTATION_SUBMITTED; form.VisitorRequest.UpdatedAt = now; db.AuditLogs.Add(new AuditLog { Id = Guid.NewGuid(), Action = "ADDITIONAL_VISITOR_FORM_SUBMITTED", EntityType = nameof(VisitorRequest), EntityId = form.VisitorRequestId, Details = $"Visitor form version {version} submitted.", CreatedAt = now }); await db.SaveChangesAsync(ct);
    }

    private static VisitorFormVersion CreateVersion(VisitorForm form, IReadOnlyList<VisitorAssetDto> assets, int version, DateTimeOffset now) => new() { Id = Guid.NewGuid(), VisitorRequestId = form.VisitorRequestId, VisitorFormId = form.Id, Version = version, FullNameSnapshot = form.FullName, CitizenshipSnapshot = form.Citizenship, CountrySnapshot = form.Country, CompanySnapshot = form.CompanyName, OfficeCitySnapshot = form.OfficeCity, OfficeCountrySnapshot = form.OfficeCountry, DesignationSnapshot = form.Designation, PhoneSnapshot = form.Telephone, EmailSnapshot = form.Email, IdTypeSnapshot = form.IdType, IdLast4Snapshot = form.IdLast4, AssetsSnapshot = JsonSerializer.Serialize(assets), CreatedAt = now };
    public async Task<(IReadOnlyList<VisitorRequestListItemDto> Items, int Total)> ListAsync(int page, int pageSize, CancellationToken ct)
    {
        var query = db.VisitorRequests.AsNoTracking().Include(r => r.Visitor).OrderByDescending(r => r.CreatedAt);
        var total = await query.CountAsync(ct); var size = Math.Clamp(pageSize, 1, 100);
        var items = await query.Skip((Math.Max(page, 1) - 1) * size).Take(size).Select(r => new VisitorRequestListItemDto(r.Id, r.RequestNumber, r.Visitor.FullName, r.VisitingCompany, r.Status.ToString(), r.CreatedAt)).ToListAsync(ct);
        return (items, total);
    }

    public async Task<VisitorRequestDetailDto?> GetAsync(Guid id, CancellationToken ct)
    {
        var request = await db.VisitorRequests.AsNoTracking().Include(r => r.Visitor).Include(r => r.VisitorForm).Include(r => r.VisitDays).Include(r => r.Assets).Include(r => r.DpsRecords).Include(r => r.EcReviews).Include(r => r.Comments).Include(r => r.InformationRequests).Include(r => r.AttendanceRecords).FirstOrDefaultAsync(r => r.Id == id, ct);
        if (request is null) return null;
        var audit = await db.AuditLogs.AsNoTracking().Where(log => log.EntityType == nameof(VisitorRequest) && log.EntityId == id).OrderByDescending(log => log.CreatedAt).Select(log => new AuditDto(log.Id, log.Action, log.EntityType, log.EntityId, log.Details, log.CreatedAt)).ToListAsync(ct);
        var versions = await db.VisitorFormVersions.AsNoTracking().Where(version => version.VisitorRequestId == id).OrderBy(version => version.Version).Select(version => new VisitorFormVersionDto(version.Id, version.Version, version.FullNameSnapshot, version.CitizenshipSnapshot, version.CountrySnapshot, version.CompanySnapshot, version.DesignationSnapshot, version.IdTypeSnapshot, version.IdLast4Snapshot, version.AssetsSnapshot, version.CreatedAt)).ToListAsync(ct);
        return ToDetail(request, audit, versions);
    }

    public async Task<VisitorRequestDetailDto> CreateAsync(CreateVisitorRequestDto input, string requesterKey, CancellationToken ct)
    {
        if (!Enum.TryParse<VisitorType>(input.VisitorType, true, out var visitorType)) throw new ArgumentException("Visitor type must be Internal or External.");
        if (input.VisitDays.Count == 0 || input.VisitDays.Any(d => d.VisitDate < DateOnly.FromDateTime(DateTime.UtcNow))) throw new ArgumentException("At least one future visit date is required.");
        if (input.VisitDays.GroupBy(d => d.VisitDate).Any(g => g.Count() > 1)) throw new ArgumentException("Visit dates must be unique.");
        var now = DateTimeOffset.UtcNow;
        var blankVisitor = new Visitor { Id = Guid.NewGuid(), VisitorType = visitorType, CreatedAt = now, UpdatedAt = now };
        var request = new VisitorRequest { Id = Guid.NewGuid(), RequestNumber = await NextRequestNumber(ct), Status = RequestStatus.VISITOR_FORM_PENDING, Visitor = blankVisitor, RequesterId = StableGuid(requesterKey), MainHostId = StableGuid(input.MainHostId), EscortingHostId = string.IsNullOrWhiteSpace(input.EscortingHostId) ? null : StableGuid(input.EscortingHostId), VisitorType = visitorType, VisitingCompany = input.VisitingCompany.Trim(), VisitingSite = input.VisitingSite.Trim(), AreasToVisit = input.AreasToVisit.Trim(), SiteTimezone = input.SiteTimezone.Trim(), NumberOfVisitors = input.NumberOfVisitors, VisitPurposeType = input.VisitPurposeType.Trim(), CreatedAt = now, UpdatedAt = now };
        var visitorForm = new VisitorForm { Id = Guid.NewGuid(), Visitor = blankVisitor, Status = "PENDING", CreatedAt = now, UpdatedAt = now };
        request.VisitorFormId = visitorForm.Id;
        request.VisitorForm = visitorForm;
        request.VisitDays = input.VisitDays.Select(d => new VisitDay { Id = Guid.NewGuid(), VisitDate = d.VisitDate, ExpectedArrivalTime = d.ExpectedArrivalTime, ExpectedDepartureTime = d.ExpectedDepartureTime, CreatedAt = now, UpdatedAt = now }).ToList();
        db.VisitorRequests.Add(request); db.AuditLogs.Add(new AuditLog { Id = Guid.NewGuid(), Action = "REQUEST_CREATED", EntityType = nameof(VisitorRequest), EntityId = request.Id, PerformedByUserId = StableGuid(requesterKey), Details = request.RequestNumber, CreatedAt = now });
        await db.SaveChangesAsync(ct); return (await GetAsync(request.Id, ct))!;
    }

    public async Task<VisitorRequestDetailDto> ExecuteActionAsync(Guid id, WorkflowActionDto input, string userId, string role, CancellationToken ct)
    {
        var request = await db.VisitorRequests.Include(r => r.Visitor).Include(r => r.VisitDays).Include(r => r.Assets).FirstOrDefaultAsync(r => r.Id == id, ct) ?? throw new KeyNotFoundException("Visitor request was not found.");
        var actor = StableGuid(userId); var action = input.Action.Trim().ToLowerInvariant(); var old = request.Status; var now = DateTimeOffset.UtcNow;
        void Role(params string[] allowed) { if (!allowed.Contains(role, StringComparer.OrdinalIgnoreCase)) throw new UnauthorizedAccessException("Your role cannot perform this action."); }
        void State(params RequestStatus[] allowed) { if (!allowed.Contains(request.Status)) throw new InvalidOperationException($"Action is not valid while the request is {request.Status}."); }
        VisitDay Day() => request.VisitDays.FirstOrDefault(day => day.Id == input.VisitDayId) ?? throw new ArgumentException("A valid visit day is required.");
        void Comment(CommentType type, string? text, bool required = false) { if (required && string.IsNullOrWhiteSpace(text)) throw new ArgumentException("A comment is required for this action."); if (!string.IsNullOrWhiteSpace(text)) db.Comments.Add(new Comment { Id = Guid.NewGuid(), VisitorRequestId = id, AuthorUserId = actor, CommentType = type, CommentText = text.Trim(), CreatedAt = now }); }
        void Notify(string type, string message, Guid user) => db.Notifications.Add(new Notification { Id = Guid.NewGuid(), UserId = user, Type = type, Message = message, CreatedAt = now });
        switch (action)
        {
            case "host-review": Role("HOST_REQUESTER"); State(RequestStatus.VISITOR_FORM_SUBMITTED); request.Status = RequestStatus.HOST_REVIEW; break;
            case "host-submit": Role("HOST_REQUESTER"); State(RequestStatus.HOST_REVIEW); request.Status = request.VisitorType == VisitorType.Internal ? RequestStatus.EC_REVIEW : (string.Equals(input.DpsPerformer, "HOST_REQUESTER", StringComparison.OrdinalIgnoreCase) ? RequestStatus.HOST_DPS : RequestStatus.EC_DPS); Notify("HOST_FINAL_SUBMITTED", "The host submitted a visitor request for compliance review.", StableGuid("prototype-export-control")); break;
            case "dps":
                var performer = string.Equals(input.DpsPerformer, "HOST_REQUESTER", StringComparison.OrdinalIgnoreCase) ? DpsPerformedByType.HOST_REQUESTER : DpsPerformedByType.EXPORT_CONTROL; Role(performer == DpsPerformedByType.HOST_REQUESTER ? "HOST_REQUESTER" : "EXPORT_CONTROL"); State(RequestStatus.HOST_DPS, RequestStatus.EC_DPS); if (!Enum.TryParse<DpsResult>(input.DpsResult ?? input.Comment, true, out var dpsResult)) throw new ArgumentException("DPS result must be Clear, Flagged, or Rejected."); db.DPSRecords.Add(new DPSRecord { Id = Guid.NewGuid(), VisitorRequestId = id, PerformedByUserId = actor, PerformedByType = performer, Status = dpsResult == DpsResult.Flagged ? DpsStatus.InProgress : DpsStatus.Completed, Result = dpsResult, PerformedAt = now, Notes = input.DpsNotes ?? input.Reason }); request.DpsPerformedBy = performer; request.Status = dpsResult == DpsResult.Rejected ? RequestStatus.REJECTED : RequestStatus.EC_REVIEW; if (dpsResult == DpsResult.Rejected) { request.RejectionReason = input.Reason; Comment(CommentType.EC_REJECTION, input.Reason, true); } break;
            case "ec-approve": Role("EXPORT_CONTROL"); State(RequestStatus.EC_REVIEW, RequestStatus.DOCUMENTATION_SUBMITTED, RequestStatus.EC_RE_REVIEW_REQUIRED, RequestStatus.RECEPTION_HOLD); db.ECReviews.Add(new ECReview { Id = Guid.NewGuid(), VisitorRequestId = id, ReviewerId = actor, Status = EcReviewStatus.Approved, Decision = EcDecision.Approve, Comments = input.Comment ?? string.Empty, ReviewedAt = now, CreatedAt = now }); request.Status = RequestStatus.APPROVED; request.ApprovedAt = now; foreach (var day in request.VisitDays.Where(day => day.Status == VisitDayStatus.RECEPTION_HOLD || day.Status == VisitDayStatus.UPCOMING)) day.Status = VisitDayStatus.UPCOMING; Notify("EC_APPROVED", "Export Control approved the visitor request.", request.RequesterId); Notify("EC_APPROVED", "An approved visitor is ready for reception.", StableGuid("prototype-reception")); break;
            case "ec-reject": Role("EXPORT_CONTROL"); State(RequestStatus.EC_REVIEW, RequestStatus.DOCUMENTATION_SUBMITTED, RequestStatus.EC_RE_REVIEW_REQUIRED, RequestStatus.RECEPTION_HOLD); if (string.IsNullOrWhiteSpace(input.Reason)) throw new ArgumentException("A rejection reason is required."); db.ECReviews.Add(new ECReview { Id = Guid.NewGuid(), VisitorRequestId = id, ReviewerId = actor, Status = EcReviewStatus.Rejected, Decision = EcDecision.Reject, Comments = input.Reason, ReviewedAt = now, CreatedAt = now }); request.Status = RequestStatus.REJECTED; request.RejectionReason = input.Reason; Comment(CommentType.EC_REJECTION, input.Reason, true); Notify("EC_REJECTED", "Export Control rejected the visitor request.", request.RequesterId); break;
            case "ec-request-documents": Role("EXPORT_CONTROL"); State(RequestStatus.EC_REVIEW, RequestStatus.EC_RE_REVIEW_REQUIRED); if (string.IsNullOrWhiteSpace(input.Reason)) throw new ArgumentException("Required information must be specified."); db.ECReviews.Add(new ECReview { Id = Guid.NewGuid(), VisitorRequestId = id, ReviewerId = actor, Status = EcReviewStatus.PendingDocumentation, Decision = EcDecision.RequestDocumentation, Comments = input.Comment ?? input.Reason, RequestedDocuments = input.Reason, CreatedAt = now }); db.Add(new AdditionalInformationRequest { Id = Guid.NewGuid(), VisitorRequestId = id, RequestedByUserId = actor, RequestedFields = input.Reason, RequestComment = input.Comment ?? input.Reason, CreatedAt = now, UpdatedAt = now }); request.Status = RequestStatus.PENDING_DOCUMENTATION; Comment(CommentType.EC_REQUEST, input.Comment ?? input.Reason, true); Notify("ADDITIONAL_INFORMATION_REQUESTED", "Additional visitor information is required.", request.RequesterId); break;
            case "submit-additional": throw new InvalidOperationException("Submit additional information through the visitor form endpoint.");
            case "personnel-change": Role("HOST_REQUESTER"); State(RequestStatus.VISITOR_FORM_SUBMITTED, RequestStatus.HOST_REVIEW); request.Status = RequestStatus.CANCELLED_PERSONNEL_CHANGE; request.PersonnelChangeRequested = true; request.PersonnelChangeRequestedAt = now; request.CancelledAt = now; Comment(CommentType.EXCEPTION, input.Reason, true); break;
            case "host-change": Role("HOST_REQUESTER"); if (string.IsNullOrWhiteSpace(input.NewUserId)) throw new ArgumentException("A new main host is required."); request.PreviousMainHostId = request.MainHostId; request.MainHostId = StableGuid(input.NewUserId); request.MainHostChangedAt = now; if (request.Status == RequestStatus.APPROVED) { request.Status = RequestStatus.EC_RE_REVIEW_REQUIRED; Comment(CommentType.HOST_CHANGE, input.Reason, true); Notify("MAIN_HOST_CHANGED", "Main host changed; Export Control review is required.", StableGuid("prototype-export-control")); } break;
            case "escort-change": Role("HOST_REQUESTER"); request.EscortingHostId = string.IsNullOrWhiteSpace(input.NewUserId) ? null : StableGuid(input.NewUserId); break;
            case "verify": Role("RECEPTION"); State(RequestStatus.APPROVED); var verifyDay = Day(); if (verifyDay.VisitDate != DateOnly.FromDateTime(DateTime.UtcNow)) throw new InvalidOperationException("Only today's visit can be verified."); if (input.IdLast4 != request.Visitor.IdLast4 || !string.Equals(input.IdType, request.Visitor.IdType, StringComparison.OrdinalIgnoreCase)) { verifyDay.Status = VisitDayStatus.ENTRY_REJECTED; Comment(CommentType.EXCEPTION, input.Reason, true); request.UpdatedAt = now; break; } verifyDay.Status = VisitDayStatus.RECEPTION_VERIFICATION; break;
            case "hold": Role("RECEPTION"); State(RequestStatus.APPROVED, RequestStatus.RECEPTION_HOLD); var holdDay = Day(); holdDay.Status = VisitDayStatus.RECEPTION_HOLD; request.Status = RequestStatus.RECEPTION_HOLD; db.Assets.Add(new Asset { Id = Guid.NewGuid(), VisitorRequestId = id, AssetType = "Undeclared asset", Description = input.Comment ?? string.Empty, SerialNumber = input.AssetSerials ?? string.Empty, IsDeclared = false, VerificationStatus = AssetVerificationStatus.Undeclared, DetectedAt = now, CreatedAt = now, UpdatedAt = now }); Comment(CommentType.UNDECLARED_ASSET, input.Comment, true); Notify("RECEPTION_HOLD", "Reception placed the visitor on hold for Export Control review.", request.RequesterId); break;
            case "check-in": Role("RECEPTION"); State(RequestStatus.APPROVED); var checkInDay = Day(); if (checkInDay.Status != VisitDayStatus.RECEPTION_VERIFICATION) throw new InvalidOperationException("Visitor identity and assets must be verified first."); if (string.IsNullOrWhiteSpace(input.BadgeNumber)) throw new ArgumentException("Badge number is required."); var badge = new Badge { Id = Guid.NewGuid(), BadgeNumber = input.BadgeNumber.Trim(), VisitorId = request.VisitorId, VisitDayId = checkInDay.Id, IssuedByUserId = actor, IssuedAt = now, Status = BadgeStatus.Issued }; db.Badges.Add(badge); db.VisitCheckIns.Add(new VisitCheckIn { Id = Guid.NewGuid(), VisitDayId = checkInDay.Id, BadgeId = badge.Id, ReceptionUserId = actor, PhysicalIdVerified = true, AssetsVerified = true, CheckedInAt = now }); checkInDay.Status = VisitDayStatus.CHECKED_IN; checkInDay.ActualArrivalTime = now; request.Status = RequestStatus.APPROVED; Notify("CHECK_IN", "Visitor checked in at reception.", request.RequesterId); break;
            case "check-out": Role("RECEPTION"); var checkOutDay = Day(); if (checkOutDay.Status != VisitDayStatus.CHECKED_IN) throw new InvalidOperationException("Only checked-in visitors can check out."); var issuedBadge = await db.Badges.FirstOrDefaultAsync(item => item.VisitDayId == checkOutDay.Id && item.Status == BadgeStatus.Issued, ct) ?? throw new InvalidOperationException("No issued badge exists for this visit day."); issuedBadge.Status = BadgeStatus.Returned; issuedBadge.ReturnedAt = now; db.VisitCheckOuts.Add(new VisitCheckOut { Id = Guid.NewGuid(), VisitDayId = checkOutDay.Id, BadgeId = issuedBadge.Id, ReceptionUserId = actor, BadgeReturned = true, Notes = input.Comment ?? string.Empty, CheckedOutAt = now }); checkOutDay.Status = VisitDayStatus.COMPLETED; checkOutDay.ActualDepartureTime = now; request.Status = request.VisitDays.Any(day => day.Status == VisitDayStatus.UPCOMING) ? RequestStatus.APPROVED : RequestStatus.VISIT_PROCESS_COMPLETED; Notify("CHECK_OUT", "Visitor checked out at reception.", request.RequesterId); break;
            case "no-show": Role("RECEPTION"); var noShowDay = Day(); if (noShowDay.Status is VisitDayStatus.CHECKED_IN or VisitDayStatus.COMPLETED) throw new InvalidOperationException("A completed visit cannot be marked no-show."); noShowDay.Status = VisitDayStatus.NO_SHOW; noShowDay.NoShowMarkedAt = now; Notify("NO_SHOW", "A visitor was marked no-show for a visit day.", request.RequesterId); Notify("NO_SHOW", "A visitor was marked no-show for a visit day.", StableGuid("prototype-export-control")); break;
            default: throw new InvalidOperationException("Unknown workflow action.");
        }
        request.UpdatedAt = now; db.AuditLogs.Add(new AuditLog { Id = Guid.NewGuid(), Action = action.ToUpperInvariant(), EntityType = nameof(VisitorRequest), EntityId = id, PerformedByUserId = actor, Details = $"{old} -> {request.Status}: {input.Comment ?? input.Reason}", CreatedAt = now }); await db.SaveChangesAsync(ct); return (await GetAsync(id, ct))!;
    }

    private async Task<string> NextRequestNumber(CancellationToken ct) { var prefix = $"RRVMS-{DateTime.UtcNow.Year}-"; var count = await db.VisitorRequests.CountAsync(r => r.RequestNumber.StartsWith(prefix), ct); return $"{prefix}{count + 1:000000}"; }
    private static Guid StableGuid(string value) => new(MD5.HashData(Encoding.UTF8.GetBytes(value)));
    private static VisitorRequestDetailDto ToDetail(VisitorRequest r, IReadOnlyList<AuditDto> audit, IReadOnlyList<VisitorFormVersionDto> versions) => new(r.Id, r.RequestNumber, new VisitorDto(r.Visitor.Id, r.Visitor.FullName, r.Visitor.CompanyName, r.Visitor.Citizenship, r.Visitor.Country, r.Visitor.Designation, r.Visitor.Email, r.Visitor.Phone, r.Visitor.IdType, r.Visitor.IdLast4, r.Visitor.VisitorType.ToString()), r.VisitPurposeType, r.VisitingCompany, r.VisitingSite, r.VisitPurposeType, r.Status.ToString(), r.VisitDays.Select(d => new VisitDayDto(d.Id, d.VisitDate, d.ExpectedArrivalTime, d.ExpectedDepartureTime, d.Status.ToString(), d.ActualArrivalTime, d.ActualDepartureTime)).ToList(), r.Assets.Select(a => new AssetDto(a.Id, a.AssetType, a.Description, a.SerialNumber, a.IsDeclared, a.IsVerified, a.VerificationStatus.ToString())).ToList(), audit, r.VisitorFormId ?? r.VisitorForm?.Id, r.DpsRecords.OrderByDescending(d => d.PerformedAt).Select(d => new DpsDto(d.Id, d.PerformedByType.ToString(), d.Status.ToString(), d.Result.ToString(), d.Notes, d.PerformedAt)).ToList(), r.EcReviews.OrderByDescending(review => review.CreatedAt).Select(review => new EcReviewDto(review.Id, review.ReviewerId, review.Status.ToString(), review.Decision.ToString(), review.Comments, review.ReviewedAt)).ToList(), r.Comments.OrderBy(comment => comment.CreatedAt).Select(comment => new CommentDto(comment.Id, comment.AuthorUserId, comment.CommentType.ToString(), comment.CommentText, comment.CreatedAt)).ToList(), r.InformationRequests.OrderBy(info => info.CreatedAt).Select(info => new InformationRequestDto(info.Id, info.RequestedFields, info.RequestComment, info.Status, info.CreatedAt, info.RespondedAt, info.ResponseSummary)).ToList(), r.AttendanceRecords.Select(record => new AttendanceDto(record.Id, record.VisitDayId, record.Category.ToString(), record.Completed, record.MarkedByUserId, record.MarkedAt, record.Comments)).ToList(), versions);
}
