// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RRVMS.Api.Data;

#nullable disable

namespace RRVMS.Api.Migrations
{
    [DbContext(typeof(RrvmsDbContext))]
    [Migration("20260826183247_AddBatchIdToVisitorRequests")]
    partial class AddBatchIdToVisitorRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RRVMS.Api.Models.AdditionalInformationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedFields")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VisitorFormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorFormId");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("AdditionalInformationRequests");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeclared")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VisitorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorId");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("RRVMS.Api.Models.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MarkedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VisitDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitDayId");

                    b.HasIndex("VisitorRequestId", "Category");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("RRVMS.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RRVMS.Api.Models.DPSRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OCRReference")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PerformedByType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("DPSRecords");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ECReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("RRVMS.Api.Models.ECReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedDocuments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("Status");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("ECReviews");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RRVMS.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AssetsVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PhysicalIdVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReceptionUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("VisitCheckIns");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitCheckOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BadgeReturned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReceptionUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("VisitCheckOuts");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("ExpectedArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ExpectedDepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset?>("NoShowMarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VisitDate");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("VisitDays");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdLast4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitorType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("FullName");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeclaredAssets")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdLast4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorId");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("VisitorForms");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorFormVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetsSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CitizenshipSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanySnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountrySnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesignationSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdLast4Snapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdTypeSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalitySnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeCitySnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeCountrySnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitorFormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorRequestId", "Version");

                    b.ToTable("VisitorFormVersions");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AreasToVisit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DpsPerformedBy")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DpsRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EscortingHostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("MainHostChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MainHostId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfVisitors")
                        .HasColumnType("integer");

                    b.Property<bool>("PersonnelChangeRequested")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PersonnelChangeRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousMainHostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteTimezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitPurposeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisitingCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisitingSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VisitorFormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitorType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("MainHostId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitorId");

                    b.ToTable("VisitorRequests");
                });

            modelBuilder.Entity("RRVMS.Api.Models.AdditionalInformationRequest", b =>
                {
                    b.HasOne("RRVMS.Api.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRVMS.Api.Models.VisitorForm", "VisitorForm")
                        .WithMany()
                        .HasForeignKey("VisitorFormId");

                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("InformationRequests")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedBy");

                    b.Navigation("VisitorForm");

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Asset", b =>
                {
                    b.HasOne("RRVMS.Api.Models.Visitor", "Visitor")
                        .WithMany("Assets")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("Assets")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.AttendanceRecord", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitDay", "VisitDay")
                        .WithMany()
                        .HasForeignKey("VisitDayId");

                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitDay");

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Comment", b =>
                {
                    b.HasOne("RRVMS.Api.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("Comments")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.DPSRecord", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("DpsRecords")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Document", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("Documents")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.ECReview", b =>
                {
                    b.HasOne("RRVMS.Api.Models.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("EcReviews")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitDay", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("VisitDays")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorForm", b =>
                {
                    b.HasOne("RRVMS.Api.Models.Visitor", "Visitor")
                        .WithMany("Forms")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("VisitorForms")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorRequest", b =>
                {
                    b.HasOne("RRVMS.Api.Models.User", null)
                        .WithMany("CreatedRequests")
                        .HasForeignKey("UserId");

                    b.HasOne("RRVMS.Api.Models.Visitor", "Visitor")
                        .WithMany("Requests")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("RRVMS.Api.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CreatedRequests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Visitor", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Forms");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorRequest", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("Comments");

                    b.Navigation("Documents");

                    b.Navigation("DpsRecords");

                    b.Navigation("EcReviews");

                    b.Navigation("InformationRequests");

                    b.Navigation("VisitDays");

                    b.Navigation("VisitorForms");
                });
#pragma warning restore 612, 618
        }
    }
}
