// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RRVMS.Api.Data;

#nullable disable

namespace RRVMS.Api.Migrations
{
    [DbContext(typeof(RrvmsDbContext))]
    partial class RrvmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RRVMS.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeclared")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("RRVMS.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("RRVMS.Api.Models.DPSRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OCRReference")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PerformedByType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("DPSRecords");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ECReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("RRVMS.Api.Models.ECReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedDocuments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("ECReviews");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RRVMS.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AssetsVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PhysicalIdVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SecurityUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("VisitCheckIns");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitCheckOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BadgeReturned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SecurityUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("VisitCheckOuts");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("ExpectedArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ExpectedDepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset?>("NoShowMarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.Property<Guid>("VisitorRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VisitDate");

                    b.HasIndex("VisitorRequestId");

                    b.ToTable("VisitDays");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdLast4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitorType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("FullName");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccompanyingEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MainHostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitPurposeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisitingCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisitingSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("MainHostId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("VisitorId");

                    b.ToTable("VisitorRequests");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Asset", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("Assets")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.DPSRecord", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("DpsRecords")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Document", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("Documents")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.ECReview", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("EcReviews")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitDay", b =>
                {
                    b.HasOne("RRVMS.Api.Models.VisitorRequest", "VisitorRequest")
                        .WithMany("VisitDays")
                        .HasForeignKey("VisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitorRequest");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorRequest", b =>
                {
                    b.HasOne("RRVMS.Api.Models.Visitor", "Visitor")
                        .WithMany("Requests")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("RRVMS.Api.Models.Visitor", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("RRVMS.Api.Models.VisitorRequest", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Documents");

                    b.Navigation("DpsRecords");

                    b.Navigation("EcReviews");

                    b.Navigation("VisitDays");
                });
#pragma warning restore 612, 618
        }
    }
}
